backend:
  name: github
  repo: Bubulahmedfoundation/bulbul-legacy-project
  branch: main

media_folder: "static/uploads"
public_folder: "/uploads"

collections:
  - name: "news"
    label: "News & Programs"
    folder: "content/news"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Date", name: "date", widget: "datetime" }
      - { label: "Body", name: "body", widget: "markdown" }
